### ISSUE TITLE
Model type `tinyllava` not recognized by Transformers

### ISSUE THREAD

**Issue by AaronChuh** [TinyLLaVA/TinyLLaVA_Factory#114]
Hi, I follow the instruction in README.md to setup the codebase and run the script provided in HuggingFace model card:

```
from transformers import AutoTokenizer, AutoModelForCausalLM

hf_path = 'Zhang199/TinyLLaVA-Qwen2-0.5B-SigLIP'
model = AutoModelForCausalLM.from_pretrained(hf_path, trust_remote_code=True)
model.cuda()
config = model.config
tokenizer = AutoTokenizer.from_pretrained(hf_path, use_fast=False, model_max_length = config.tokenizer_model_max_length,padding_side = config.tokenizer_padding_side)
prompt="What are these?"
image_url="http://images.cocodataset.org/test-stuff2017/000000000001.jpg"
output_text, genertaion_time = model.chat(prompt=prompt, image=image_url, tokenizer=tokenizer)

print('model output:', output_text)
print('runing time:', genertaion_time)
```
print('runing time:', genertaion_time)

But I got error:
```
Traceback (most recent call last):
  File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 945, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 647, in __getitem__
    raise KeyError(key)
KeyError: 'tinyllava'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/code/TinyLLaVA/demo.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained(path, trust_remote_code=True)
  File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 947, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `tinyllava` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```

Here is my environment:
```
Package                   Version     Editable project location
------------------------- ----------- ----------------------------------
accelerate                0.27.2
aiofiles                  24.1.0
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
altair                    5.4.1
anyio                     4.4.0
async-timeout             4.0.3
attrs                     24.2.0
bitsandbytes              0.41.0
certifi                   2024.8.30
charset-normalizer        3.3.2
click                     8.1.7
cmake                     3.30.3
contourpy                 1.3.0
cycler                    0.12.1
deepspeed                 0.14.0
docker-pycreds            0.4.0
einops                    0.6.1
einops-exts               0.0.4
et-xmlfile                1.1.0
exceptiongroup            1.2.2
fastapi                   0.114.0
ffmpy                     0.4.0
filelock                  3.16.0
flash-attn                2.6.3
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.9.0
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    3.35.2
gradio_client             0.2.9
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.24.6
idna                      3.8
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.7
latex2mathml              3.77.0
linkify-it-py             2.0.3
lit                       18.1.8
markdown-it-py            2.2.0
markdown2                 2.5.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.1.0
narwhals                  1.6.4
networkx                  3.3
ninja                     1.11.1.1
numpy                     1.26.4
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
openpyxl                  3.1.5
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.2
peft                      0.10.0
pillow                    10.4.0
pip                       24.2
platformdirs              4.3.2
protobuf                  5.28.0
psutil                    6.0.0
py-cpuinfo                9.0.0
pydantic                  1.10.18
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.3
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rpds-py                   0.20.0
safetensors               0.4.5
scikit-learn              1.2.2
scipy                     1.14.1
semantic-version          2.10.0
sentencepiece             0.1.99
sentry-sdk                2.14.0
setproctitle              1.3.3
setuptools                72.1.0
shortuuid                 1.0.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
starlette                 0.38.5
svgwrite                  1.4.3
sympy                     1.13.2
tensorboardX              2.6.2.2
threadpoolctl             3.5.0
tiktoken                  0.7.0
timm                      0.6.13
tinyllava                 1.0.0       /home/aaron/code/TinyLLaVA_Factory
tokenizers                0.19.0
torch                     2.0.1
torchvision               0.15.2
tqdm                      4.66.5
transformers              4.40.1
triton                    2.0.0
typing_extensions         4.12.2
tzdata                    2024.1
uc-micro-py               1.0.3
urllib3                   2.2.2
uvicorn                   0.30.6
wandb                     0.17.9
wavedrom                  2.0.3.post3
websockets                13.0.1
wheel                     0.43.0
yarl                      1.11.1
```

Thanks for any possible help!

**Comment by perp** [comment]
> Hi, I follow the instruction in README.md to setup the codebase and run the script provided in HuggingFace model card:
> 
> ```
> from transformers import AutoTokenizer, AutoModelForCausalLM
> 
> hf_path = 'Zhang199/TinyLLaVA-Qwen2-0.5B-SigLIP'
> model = AutoModelForCausalLM.from_pretrained(hf_path, trust_remote_code=True)
> model.cuda()
> config = model.config
> tokenizer = AutoTokenizer.from_pretrained(hf_path, use_fast=False, model_max_length = config.tokenizer_model_max_length,padding_side = config.tokenizer_padding_side)
> prompt="What are these?"
> image_url="http://images.cocodataset.org/test-stuff2017/000000000001.jpg"
> output_text, genertaion_time = model.chat(prompt=prompt, image=image_url, tokenizer=tokenizer)
> 
> print('model output:', output_text)
> print('runing time:', genertaion_time)
> ```
> 
> print('runing time:', genertaion_time)
> 
> But I got error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 945, in from_pretrained
>     config_class = CONFIG_MAPPING[config_dict["model_type"]]
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 647, in __getitem__
>     raise KeyError(key)
> KeyError: 'tinyllava'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/aaron/code/TinyLLaVA/demo.py", line 4, in <module>
>     model = AutoModelForCausalLM.from_pretrained(path, trust_remote_code=True)
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
>     config, kwargs = AutoConfig.from_pretrained(
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 947, in from_pretrained
>     raise ValueError(
> ValueError: The checkpoint you are trying to load has model type `tinyllava` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
> ```
> 
> Here is my environment:
> 
> ```
> Package                   Version     Editable project location
> ------------------------- ----------- ----------------------------------
> accelerate                0.27.2
> aiofiles                  24.1.0
> aiohappyeyeballs          2.4.0
> aiohttp                   3.10.5
> aiosignal                 1.3.1
> altair                    5.4.1
> anyio                     4.4.0
> async-timeout             4.0.3
> attrs                     24.2.0
> bitsandbytes              0.41.0
> certifi                   2024.8.30
> charset-normalizer        3.3.2
> click                     8.1.7
> cmake                     3.30.3
> contourpy                 1.3.0
> cycler                    0.12.1
> deepspeed                 0.14.0
> docker-pycreds            0.4.0
> einops                    0.6.1
> einops-exts               0.0.4
> et-xmlfile                1.1.0
> exceptiongroup            1.2.2
> fastapi                   0.114.0
> ffmpy                     0.4.0
> filelock                  3.16.0
> flash-attn                2.6.3
> fonttools                 4.53.1
> frozenlist                1.4.1
> fsspec                    2024.9.0
> gitdb                     4.0.11
> GitPython                 3.1.43
> gradio                    3.35.2
> gradio_client             0.2.9
> h11                       0.14.0
> hjson                     3.1.0
> httpcore                  0.17.3
> httpx                     0.24.0
> huggingface-hub           0.24.6
> idna                      3.8
> Jinja2                    3.1.4
> joblib                    1.4.2
> jsonschema                4.23.0
> jsonschema-specifications 2023.12.1
> kiwisolver                1.4.7
> latex2mathml              3.77.0
> linkify-it-py             2.0.3
> lit                       18.1.8
> markdown-it-py            2.2.0
> markdown2                 2.5.0
> MarkupSafe                2.1.5
> matplotlib                3.9.2
> mdit-py-plugins           0.3.3
> mdurl                     0.1.2
> mpmath                    1.3.0
> multidict                 6.1.0
> narwhals                  1.6.4
> networkx                  3.3
> ninja                     1.11.1.1
> numpy                     1.26.4
> nvidia-cublas-cu11        11.10.3.66
> nvidia-cuda-cupti-cu11    11.7.101
> nvidia-cuda-nvrtc-cu11    11.7.99
> nvidia-cuda-runtime-cu11  11.7.99
> nvidia-cudnn-cu11         8.5.0.96
> nvidia-cufft-cu11         10.9.0.58
> nvidia-curand-cu11        10.2.10.91
> nvidia-cusolver-cu11      11.4.0.1
> nvidia-cusparse-cu11      11.7.4.91
> nvidia-nccl-cu11          2.14.3
> nvidia-nvtx-cu11          11.7.91
> openpyxl                  3.1.5
> orjson                    3.10.7
> packaging                 24.1
> pandas                    2.2.2
> peft                      0.10.0
> pillow                    10.4.0
> pip                       24.2
> platformdirs              4.3.2
> protobuf                  5.28.0
> psutil                    6.0.0
> py-cpuinfo                9.0.0
> pydantic                  1.10.18
> pydub                     0.25.1
> Pygments                  2.18.0
> pynvml                    11.5.3
> pyparsing                 3.1.4
> python-dateutil           2.9.0.post0
> python-multipart          0.0.9
> pytz                      2024.1
> PyYAML                    6.0.2
> referencing               0.35.1
> regex                     2024.7.24
> requests                  2.32.3
> rpds-py                   0.20.0
> safetensors               0.4.5
> scikit-learn              1.2.2
> scipy                     1.14.1
> semantic-version          2.10.0
> sentencepiece             0.1.99
> sentry-sdk                2.14.0
> setproctitle              1.3.3
> setuptools                72.1.0
> shortuuid                 1.0.13
> six                       1.16.0
> smmap                     5.0.1
> sniffio                   1.3.1
> starlette                 0.38.5
> svgwrite                  1.4.3
> sympy                     1.13.2
> tensorboardX              2.6.2.2
> threadpoolctl             3.5.0
> tiktoken                  0.7.0
> timm                      0.6.13
> tinyllava                 1.0.0       /home/aaron/code/TinyLLaVA_Factory
> tokenizers                0.19.0
> torch                     2.0.1
> torchvision               0.15.2
> tqdm                      4.66.5
> transformers              4.40.1
> triton                    2.0.0
> typing_extensions         4.12.2
> tzdata                    2024.1
> uc-micro-py               1.0.3
> urllib3                   2.2.2
> uvicorn                   0.30.6
> wandb                     0.17.9
> wavedrom                  2.0.3.post3
> websockets                13.0.1
> wheel                     0.43.0
> yarl                      1.11.1
> ```
> 
> Thanks for any possible help!

how did you sovled this problem?

**Comment by MichealZhangxa** [comment]
> Hi, I follow the instruction in README.md to setup the codebase and run the script provided in HuggingFace model card:
> 
> ```
> from transformers import AutoTokenizer, AutoModelForCausalLM
> 
> hf_path = 'Zhang199/TinyLLaVA-Qwen2-0.5B-SigLIP'
> model = AutoModelForCausalLM.from_pretrained(hf_path, trust_remote_code=True)
> model.cuda()
> config = model.config
> tokenizer = AutoTokenizer.from_pretrained(hf_path, use_fast=False, model_max_length = config.tokenizer_model_max_length,padding_side = config.tokenizer_padding_side)
> prompt="What are these?"
> image_url="http://images.cocodataset.org/test-stuff2017/000000000001.jpg"
> output_text, genertaion_time = model.chat(prompt=prompt, image=image_url, tokenizer=tokenizer)
> 
> print('model output:', output_text)
> print('runing time:', genertaion_time)
> ```
> 
> print('runing time:', genertaion_time)
> 
> But I got error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 945, in from_pretrained
>     config_class = CONFIG_MAPPING[config_dict["model_type"]]
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 647, in __getitem__
>     raise KeyError(key)
> KeyError: 'tinyllava'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/aaron/code/TinyLLaVA/demo.py", line 4, in <module>
>     model = AutoModelForCausalLM.from_pretrained(path, trust_remote_code=True)
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
>     config, kwargs = AutoConfig.from_pretrained(
>   File "/home/aaron/anaconda3/envs/tinyllava_factory/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 947, in from_pretrained
>     raise ValueError(
> ValueError: The checkpoint you are trying to load has model type `tinyllava` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
> ```
> 
> Here is my environment:
> 
> ```
> Package                   Version     Editable project location
> ------------------------- ----------- ----------------------------------
> accelerate                0.27.2
> aiofiles                  24.1.0
> aiohappyeyeballs          2.4.0
> aiohttp                   3.10.5
> aiosignal                 1.3.1
> altair                    5.4.1
> anyio                     4.4.0
> async-timeout             4.0.3
> attrs                     24.2.0
> bitsandbytes              0.41.0
> certifi                   2024.8.30
> charset-normalizer        3.3.2
> click                     8.1.7
> cmake                     3.30.3
> contourpy                 1.3.0
> cycler                    0.12.1
> deepspeed                 0.14.0
> docker-pycreds            0.4.0
> einops                    0.6.1
> einops-exts               0.0.4
> et-xmlfile                1.1.0
> exceptiongroup            1.2.2
> fastapi                   0.114.0
> ffmpy                     0.4.0
> filelock                  3.16.0
> flash-attn                2.6.3
> fonttools                 4.53.1
> frozenlist                1.4.1
> fsspec                    2024.9.0
> gitdb                     4.0.11
> GitPython                 3.1.43
> gradio                    3.35.2
> gradio_client             0.2.9
> h11                       0.14.0
> hjson                     3.1.0
> httpcore                  0.17.3
> httpx                     0.24.0
> huggingface-hub           0.24.6
> idna                      3.8
> Jinja2                    3.1.4
> joblib                    1.4.2
> jsonschema                4.23.0
> jsonschema-specifications 2023.12.1
> kiwisolver                1.4.7
> latex2mathml              3.77.0
> linkify-it-py             2.0.3
> lit                       18.1.8
> markdown-it-py            2.2.0
> markdown2                 2.5.0
> MarkupSafe                2.1.5
> matplotlib                3.9.2
> mdit-py-plugins           0.3.3
> mdurl                     0.1.2
> mpmath                    1.3.0
> multidict                 6.1.0
> narwhals                  1.6.4
> networkx                  3.3
> ninja                     1.11.1.1
> numpy                     1.26.4
> nvidia-cublas-cu11        11.10.3.66
> nvidia-cuda-cupti-cu11    11.7.101
> nvidia-cuda-nvrtc-cu11    11.7.99
> nvidia-cuda-runtime-cu11  11.7.99
> nvidia-cudnn-cu11         8.5.0.96
> nvidia-cufft-cu11         10.9.0.58
> nvidia-curand-cu11        10.2.10.91
> nvidia-cusolver-cu11      11.4.0.1
> nvidia-cusparse-cu11      11.7.4.91
> nvidia-nccl-cu11          2.14.3
> nvidia-nvtx-cu11          11.7.91
> openpyxl                  3.1.5
> orjson                    3.10.7
> packaging                 24.1
> pandas                    2.2.2
> peft                      0.10.0
> pillow                    10.4.0
> pip                       24.2
> platformdirs              4.3.2
> protobuf                  5.28.0
> psutil                    6.0.0
> py-cpuinfo                9.0.0
> pydantic                  1.10.18
> pydub                     0.25.1
> Pygments                  2.18.0
> pynvml                    11.5.3
> pyparsing                 3.1.4
> python-dateutil           2.9.0.post0
> python-multipart          0.0.9
> pytz                      2024.1
> PyYAML                    6.0.2
> referencing               0.35.1
> regex                     2024.7.24
> requests                  2.32.3
> rpds-py                   0.20.0
> safetensors               0.4.5
> scikit-learn              1.2.2
> scipy                     1.14.1
> semantic-version          2.10.0
> sentencepiece             0.1.99
> sentry-sdk                2.14.0
> setproctitle              1.3.3
> setuptools                72.1.0
> shortuuid                 1.0.13
> six                       1.16.0
> smmap                     5.0.1
> sniffio                   1.3.1
> starlette                 0.38.5
> svgwrite                  1.4.3
> sympy                     1.13.2
> tensorboardX              2.6.2.2
> threadpoolctl             3.5.0
> tiktoken                  0.7.0
> timm                      0.6.13
> tinyllava                 1.0.0       /home/aaron/code/TinyLLaVA_Factory
> tokenizers                0.19.0
> torch                     2.0.1
> torchvision               0.15.2
> tqdm                      4.66.5
> transformers              4.40.1
> triton                    2.0.0
> typing_extensions         4.12.2
> tzdata                    2024.1
> uc-micro-py               1.0.3
> urllib3                   2.2.2
> uvicorn                   0.30.6
> wandb                     0.17.9
> wavedrom                  2.0.3.post3
> websockets                13.0.1
> wheel                     0.43.0
> yarl                      1.11.1
> ```
> 
> Thanks for any possible help!

How did you solve this problem?
