### ISSUE TITLE
After reading "readme.md for qwen2"

### ISSUE THREAD

**Issue by joony414** [TinyLLaVA/TinyLLaVA_Factory#119]
Hello guys.
First of all, I want to thank you guys for great works on TinyLLaVA Factory.

As you guys mentioned in "readme.md for qwen2"
I'm trying to make model with Qwen2-7B-Instruct and it seems there are error
such as below when running the training script

```
Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))  
==== backtrace (tid: 8601) ====
0 0x0000000000042520 __sigaction() ???:0
======================
```

It would be greatful if you guys share the knowledge how to train other qwen2 model

**Comment by joony414** [comment]
Never mind. It turns out that the problem was the GPU server's low linux kernel version.
After I upgrade the GPU server, it works fine.

**Comment by YingHuTsing** [comment]
This issue seems not specific to the Qwen2 model. But if you want to train Qwen2 -7B by TinyLLaVA factory please feel to contact us.
