### ISSUE TITLE
EnvironmentError: Accessing Gated Repo in train_openelm.sh

### ISSUE THREAD

**Issue by YenCheHsiao** [TinyLLaVA/TinyLLaVA_Factory#130]
I encountered an error when trying to run the train_openelm.sh script located in the /scripts/train/openelm/ directory.

Error Message:
```
raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-2-7b-hf.
401 Client Error. (Request ID: Root=1-67303e7c-1818e87c26db738f0953207d;29973a37-62d7-4984-8699-f02587ba247d)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-hf/resolve/main/config.json.
Access to model meta-llama/Llama-2-7b-hf is restricted. You must have access to it and be authenticated to access it. Please log in.
```

Could you provide guidance on how to add the Hugging Face access token for the Llama-2-7b-hf model?

**Comment by ZhangXJ199** [comment]
You can obtain your token from "https://huggingface.co/settings/tokens".

**Comment by ZhangXJ199** [comment]
You can use the command "huggingface-cli download --token hf_*** --resume-download meta-llama/Llama-2-7b-hf --local-dir Llama-2-7b-hf" to download the model to a specified location, and then modify the script path accordingly.
