### ISSUE TITLE
请问MM-Vet 看的是total指标对嘛

### ISSUE THREAD

**Issue by Danield21** [TinyLLaVA/TinyLLaVA_Factory#161]
作者您好，

MM-Vet 经过线上评测下来，得到了若干个指标结果，有rec,ocr,know,gen,spat,math,total。请问在paper里，你们汇报的是total指标对嘛

Thanks！

**Comment by ZhangXJ199** [comment]
是的

**Comment by Danield21** [comment]
谢谢您的答复，

请教一个following question。

请问如果想要基于Qwen1.5 作为 llm模块，可以直接以qwen2_base来设置CONV_VERSION嘛

**Comment by ZhangXJ199** [comment]
可以
