### ISSUE TITLE
Request for Weights of apple/OpenELM-450M-Instruct Model

### ISSUE THREAD

**Issue by rotem154154** [TinyLLaVA/TinyLLaVA_Factory#61]
Great work!

I noticed in the "Model Performance" table that there are several models listed which haven't been released. Could you please share the weights for the model trained with the LLM apple/OpenELM-450M-Instruct?

Thanks!

**Comment by shiym2000** [comment]
You can find it at https://huggingface.co/apple/OpenELM-450M-Instruct

**Comment by YingHuTsing** [comment]
> Thank you for your response. However, I am specifically looking for the TinyLLaVA model that was built using the LLM apple/OpenELM-450M-Instruct. The link you provided points to the LLM itself, but not the TinyLLaVA model weights. Could you please share the weights for the TinyLLaVA model?
> 
> Thanks!

Thanks for following our work! We have released it (the TinyLLaVA model that was built using the LLM apple/OpenELM-450M-Instruct) on HuggingFace, you can find it here 

https://huggingface.co/jiajunlong/TinyLLaVA-0.89B
