### ISSUE TITLE
ModuleNotFoundError: No module named 'tinyllava.model.builder'

### ISSUE THREAD

**Issue by dkjung** [TinyLLaVA/TinyLLaVA_Factory#63]
Hi, guys

When I tried to use your model for inference, I faced ModuleNotFoundError.

I did install TinyLLaVa as `README.md` tells, with the following command at the root directory of the git repository.
(Basically I did it in a docker container, so I didn't use conda environment.)

```
pip install -e .
```

It's done with some warnings, but they looked minor.

With that, I launched `jupyter lab` at the repository's root directory and wrote the following line in a cell and run.

```Python
from tinyllava.model.builder import load_pretrained_model
```

However, I encountered the following error message.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 from tinyllava.model.builder import load_pretrained_model

ModuleNotFoundError: No module named 'tinyllava.model.builder'
```

Plus, there is directory with path `tinyllava/model` under the root directory, but `tinyllava/model/builder` does not exist.

How can I resolve this error?

**Comment by jiajunlong** [comment]
It seems you are using the tinyllava_bench branch version of the inference code. Please refer to the "Launch Demo Locally" section in the readme for the new version of the inference code.

**Comment by dkjung** [comment]
@jiajunlong Thanks!

**Comment by dkjung** [comment]
It works
