### ISSUE TITLE
Question about  'fix everything'

### ISSUE THREAD

**Issue by Zeqing-Wang** [TinyLLaVA/TinyLLaVA_Factory#71]
Hi! Thanks for your great work. I find there are some random things in TinyLLaVA(eg, the dataloader). I wonder is there any setting I can change to fix the random seed?

**Comment by YingHuTsing** [comment]
Hi, please set random seed just like other programs do, e.g. in the beginning of the train() function in tinyllava/train/train.py

**Comment by jiajunlong** [comment]
You don't need to manually set the random seed. The Trainer in transformers will help to set the seed. For the specific code, see [line 398 in the trainer.py](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L398) (the default value of full_determinism is False). You can set the seed value in args.

**Comment by Zeqing-Wang** [comment]
> You don't need to manually set the random seed. The Trainer in transformers will help to set the seed. For the specific code, see [line 398 in the trainer.py](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L398) (the default value of full_determinism is False). You can set the seed value in args.

Thanks, I solved it.

**Comment by Zeqing-Wang** [comment]
Issue has been solved
