### ISSUE TITLE
template differences？

### ISSUE THREAD

**Issue by Murasame-sway** [TinyLLaVA/TinyLLaVA_Factory#77]
Are there any differences in the _make_masks function across different LLM models? Don't they all compute loss only for the response part? What causes the variations among them?

**Comment by jiajunlong** [comment]
Different models use different tokenizers, and when different tokenizers tokenize the text, the corresponding label positions are different.

**Comment by exiawsh** [comment]
@jiajunlong  Hi. Does llama2, tinyllama and vicuna share the same template? Sorry to bother you.
