### ISSUE TITLE
share training recipe

### ISSUE THREAD

**Issue by Fantasy1120** [TinyLLaVA/TinyLLaVA_Factory#80]
Does this version support share training recipe? I noticed that you have set ` --tune_type_llm frozen,  --tune_type_vision_tower frozen`  in your scripts, and you also set `self.language_model.requires_grad_(False), self._vision_tower.requires_grad_(False) `when loading the model for pre-training.

**Comment by YingHuTsing** [comment]
Yes, this version supports share recipe. Please refer to scripts/train/share/train_phi_share.sh. In scripts/train/share/pretrain_share.sh, we set --tune_type_llm full.
