### ISSUE TITLE
Gemma template for integrating instruct tuned model

### ISSUE THREAD

**Issue by Jayantverma2** [TinyLLaVA/TinyLLaVA_Factory#96]
There are "additional_special_tokens": [
    "<start_of_turn>",
    "<end_of_turn>"
  ]   in gemma, should we use start_of_turn before start of text of both user ans assistantand end of turn after completing the conversation of each.  Where as in your template you have used only bos and eos  tokens 
  format_image_token: "Formatter" = StringFormatter(slot="<image>\n{{content}}")
    format_user: "Formatter" = StringFormatter(slot="USER" + ": " + "{{content}}" + " ")
    format_assistant: "Formatter" = StringFormatter(slot="ASSISTANT" + ": " + "{{content}}" + "<eos>")
    system: "Formatter" = EmptyFormatter(slot=system+" ")
    separator: "Formatter" = EmptyFormatter(slot=[' A
SSISTANT: ', '<eos>'])
![Screenshot from 2024-07-16 19-35-49](https://github.com/user-attachments/assets/fcef59d5-d679-4b06-bf70-4c4eac1de9da)
ref: https://huggingface.co/google/gemma-2-9b-it

**Comment by shiym2000** [comment]
Yes, the implementation by TinyLLaVA_Factory is correct if we only consider the tokenizer's encoding method. However, during gemma's training process, additional <start_of_turn> and <end_of_turn> tokens might be added outside each round of dialogue. Including these tokens might slightly improve performance. You can customize a template to test this.
